-- DROP DATABASE IF EXISTS LOJA_BRINQUEDOS;

CREATE DATABASE IF NOT EXISTS LOJA_BRINQUEDOS CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI;

USE LOJA_BRINQUEDOS;

CREATE TABLE IF NOT EXISTS CATEGORIAS(
	ID 			INT				AUTO_INCREMENT,
    NOME		VARCHAR(100)	NOT NULL,
    URL_FOTO	VARCHAR(250)	NOT NULL,
    
    CONSTRAINT PK_CATEGORIA PRIMARY KEY (ID)
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS BRINQUEDOS(
	ID				INT				AUTO_INCREMENT,
    DESCRICAO		VARCHAR(100)	NOT NULL,
    ID_CATEGORIA	INT				NOT NULL,
    MARCA			VARCHAR(100)	NOT NULL,
    URL_FOTO		VARCHAR(250)	NOT NULL,
    VALOR			DECIMAL(5,2)	NOT NULL,
    DETALHES 		TEXT			NOT NULL,
    
    CONSTRAINT PK_BRINQUEDOS PRIMARY KEY (ID),
    CONSTRAINT FK_CATEGORIA_2_BRINQUEDOS FOREIGN KEY (ID_CATEGORIA) REFERENCES LOJA_BRINQUEDOS.CATEGORIAS (ID)
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS USERS(
	ID 			INT				NOT NULL AUTO_INCREMENT,
    LOGIN		VARCHAR(100)	NOT NULL,
    PASSWORD	VARCHAR(100)	NOT NULL,
    
    CONSTRAINT PK_USERS PRIMARY KEY (ID)
)ENGINE=InnoDB;
